### PR TITLE
Handle SparseArrays.jl dep as Pkg extension

### PR DESCRIPTION
**Pull request by dkarrasch**
I wonder if we want to/can/should backport this to v1.9 and v1.10?

### CODE REVIEW

**Comment by dkarrasch** [comment]
Well, backporting to v1.9 doesn't make much sense, I guess, since SparseArrays.jl is in the sysimage. But backporting to v1.10 is important.

**Comment by dkarrasch** [comment]
Uff, I only now realize this is a duplicate of #134. What needs to be done to get this done? Not having SparseArrays.jl as a weak dependency puts a heavy load (time) on downstream packages like Distances.jl.

**Comment by nalimilan** [comment]
Not sure. If it is confirmed that weak dependencies don't work for stdlib modules, we will have to finish https://github.com/JuliaLang/julia/pull/46501 first.

**Comment by dkarrasch** [comment]
Right, but the Statistics.jl dependency is not touched here. We only make the direct dependency on SparseArrays.jl weak.

**Pull request closed without merging**
